import React from 'react'
export const metadata = {
    title:"میزکار کاظم",
    description: "Generated by create next app",
  };
  export default function RootLayout({ children }) {
  return (
    
    <div>{children}</div>
  )
}
