import { Vazirmatn } from "next/font/google";
import "./globals.css";

const vazirmatn = Vazirmatn({ subsets: ["latin"] });

export const metadata = {
  title: "کاظم | ناموس هرچی ای‌آر‌پی",
  description: "Generated by create next app",
};
//TODO config pwa
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="192x192" href="/icons/icon-192x192.png" />
        <link rel="apple-touch-icon" sizes="512x512" href="/icons/icon-512x512.png" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body className={vazirmatn.className}>{children}</body>
    </html>
  );
}
